### ISSUE TITLE
ruby.wasm doesn't work on Wasmer 3.0

### ISSUE THREAD

**Issue by koduki** [ruby/ruby.wasm#116]
# Summary
I tried to execute ruby.wasm via below commands on wasmer 3.0.1, but it doesn't work.

```sh
$ wasmer --version
wasmer 3.0.1
$ wasmer run ./ruby.wasm -- --version
thread 'main' panicked at 'not yet implemented: could not serialize number 2 to enum Clockid', lib/wasi-types/src/wasi/extra.rs:2725:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It worked on wasmer 2.3.0 and wasmtime 3.0.0.

```sh
$ curl https://get.wasmer.io -sSfL | sh -s "2.3.0"
$ wasmer --version
wasmer 2.3.0
$ wasmer run ./ruby.wasm -- --version
ruby 3.2.0dev (2022-11-11T22:40:31Z master 0a9d51ee9d) [wasm32-wasi]
```

```sh
$ wasmtime --version
wasmtime-cli 3.0.0
$ wasmtime run ./ruby.wasm -- --version
ruby 3.2.0dev (2022-11-11T22:40:31Z master 0a9d51ee9d) [wasm32-wasi]
````

I don't have confidence this issue is ruby problem or wasmer problem, but wasmer 3.0.2 can execute some WASM which are created by Rust. So, I report it here.

# Environments and install

## OS
[3.2.0-preview3-bullseye(Docker)](https://github.com/docker-library/ruby/blob/09ae96ae70997acb44bac52df46e015755b228e1/3.2-rc/bullseye/Dockerfile)

## ruby.wasm

```sh
$ curl -LO https://github.com/ruby/ruby.wasm/releases/latest/download/ruby-head-wasm32-unknown-wasi-full.tar.gz
$ tar xfz ruby-head-wasm32-unknown-wasi-full.tar.gz
$ mv head-wasm32-unknown-wasi-full/usr/local/bin/ruby ruby.wasm
```

## wasmer

```sh
$ curl https://get.wasmer.io -sSfL | sh
$ wasmer --version
wasmer 3.0.1
```

# Expectation

success to run ruby.wasm

```sh
$ wasmer run ./ruby.wasm -- --version
ruby 3.2.0dev (2022-11-11T22:40:31Z master 0a9d51ee9d) [wasm32-wasi]
```

# Actual Error

```sh
$ wasmer run ./ruby.wasm -- --version
thread 'main' panicked at 'not yet implemented: could not serialize number 2 to enum Clockid', lib/wasi-types/src/wasi/extra.rs:2725:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by kateinoigakukun** [comment]
Thanks for reporting. This is apparently wasmer's issue because wasmer 3.0.2 has incompatibilities with WASI spec for now.
Wasmer is mixing [legacy ABI and latest ABI for clock id]( https://github.com/wasmerio/wasmer/blob/5287c4f1253f66f428066d35eef0825fe827cff3/lib/wasi/src/syscalls/mod.rs#L382), and Ruby uses a clock id defined only in the latest ABI.
I know it would be a practical issue because wasmer is one of the most popular wasm runtimes unfortunately, but I don't want to introduce workarounds only for a specific runtime.

Could you report it to wasmer side?

**Comment by koduki** [comment]
Thank you for your reply and forward issue to wasmer! Should I close this project?

**Comment by kateinoigakukun** [comment]
Looks like it's fixed on wasmer side :)
