### ISSUE TITLE
[Documentation] Call wasm imports

### ISSUE THREAD

**Issue by rkh** [ruby/ruby.wasm#13]
Not sure this is the right place to ask, but is there a way to call imported wasm functions directly (or if not, indirectly) from Ruby?

**Comment by kateinoigakukun** [comment]
@rkh Unfortunately, there is no easy way to call imported wasm functions directly with pre-compiled ruby.wasm since these import entries have to be determined statically during linking-time, and wasm doesn't support dynamic linking yet.
You need to build an extension library to call imported functions from Ruby script as [`ext/js` does](https://github.com/ruby/ruby.wasm/tree/main/ext/js), then link it against `ruby.wasm`.

Sorry for the lack of documentation :bow:
