### ISSUE TITLE
'Function not implemented' error on requiring gems from mounted FS

### ISSUE THREAD

**Issue by skryukov** [ruby/ruby.wasm#17]
Hey @kateinoigakukun! Thanks for your work on ruby.wasm, I have a lot of fun playing with it!

Currently, I'm trying to add a gem to the `wasmer` instance right from the JS. `File.read` works fine, but if I'm trying to call `require 'dry-initializer'`, I'm getting such error message:

```ruby
# /usr/local/lib/ruby_gems is a custom dirrectory
puts File.read '/usr/local/lib/ruby_gems/dry-initializer-3.1.1/lib/dry-initializer.rb'
# =>
# # frozen_string_literal: true
#
# require_relative "dry/initializer"
require 'dry-initializer'
# =>
# Error: eval:3:in `require': Function not implemented -- /usr/local/lib/ruby_gems/dry-initializer-3.1.1/lib/dry-initializer.rb (LoadError)
# eval:3:in `<main>'
```

I can't find the source of this `Function not implemented` message, maybe you have an idea what is going on, and how may I found the source of the problem?

Here is a project with reproduction: https://github.com/skryukov/ruby-wasi-playground

**Comment by kateinoigakukun** [comment]
Thank you for the report!

I investigated further and found that the `@wasmer/wasi` polyfill doesn't implement `fd_fdstat_set_flags` system call, which is used while `require`:
https://github.com/wasmerio/wasmer-js/blob/55fa8c17c56348c312a8bd23c69054b1aa633891/packages/wasi/src/index.ts#L617-L620

FYI: You can see which system call return error by the following snippet 

```js
const traceSyscall = (wasiObject) => {
  for (const key in wasiObject.wasiImport) {
    const func = wasiObject.wasiImport[key]
    wasiObject.wasiImport[key] = function() {
      const ret = Reflect.apply(func, undefined, arguments);
      if (ret != 0) {
        console.log(`[tracing] WASI.${key} returns ${ret}`);
      }
      return ret;
    }
  }
}

const main = async () => {
  const wasi = new WASI(...);
  traceSyscall(wasi);

  const ruby = new RubyVM();
  const imports = { wasi_snapshot_preview1: wasi.wasiImport };
  ruby.addToImports(imports);
  ...
}
```

Since the use of the syscall is only for synchronization things, it's no use under the single thread assumption, so it's ok to replace the implementation with just returning 0.

**Comment by skryukov** [comment]
Wow, it works now! Thanks for the snippet, that's insanely helpful 🙏
