### ISSUE TITLE
`RbError: SystemStackError: stack level too deep` when using `require 'json'` with `vm.evalAsync`

### ISSUE THREAD

**Issue by terrablue** [ruby/ruby.wasm#340]
If I try to use `require 'json'` with `vm.evalAsync`, I get a `RbError: SystemStackError: stack level too deep` error.

No error if I use `vm.eval`.

Example code (with 3.2):

```js
await vm.evalAsync("require 'json'");
```

In this case, I'm using the `node_modules/@ruby/3.2-wasm-wasi/dist/ruby+stdlib.wasm` file to get the JSON module.

**Comment by kateinoigakukun** [comment]
You need some workaround to address 3.2-specific issue like below:

```
<html>
  <script type="module">
    import { DefaultRubyVM } from "https://cdn.jsdelivr.net/npm/@ruby/wasm-wasi@2.4.0/dist/browser/+esm";
    const response = await fetch("https://cdn.jsdelivr.net/npm/@ruby/3.2-wasm-wasi@2.4.0/dist/ruby+stdlib.wasm");
    const module = await WebAssembly.compileStreaming(response);
    const { vm } = await DefaultRubyVM(module, { env: {
      "RUBY_FIBER_MACHINE_STACK_SIZE": "8388608"
    }});

    await vm.evalAsync("require 'json'; puts :ok");
  </script>
</html>
```

`browser.script.iife.js` contains the workaround, but `browser.js` doesn't since it's Ruby version independent, so you need to put it manually: https://github.com/ruby/ruby.wasm/blob/b0c4f7bef3c35249d15acba2c2a0cc29851b5dd2/packages/npm-packages/ruby-3.2-wasm-wasi/src/browser.script.js#L4-L12

**Comment by terrablue** [comment]
I see. I'm using it with NodeJS though, sorry if that was unclear. Would I pass the same options to `DefaultRubyVM` there too?

Alternatively I'll just switch to head.

**Comment by kateinoigakukun** [comment]
The same option is also available for node.js

**Comment by terrablue** [comment]
Thanks, that worked!
